### ISSUE TITLE
Detach observer

### ISSUE THREAD

**Issue by dy** [WebReflection/attributechanged#3]
I've planned to use that as dependency in package, but there seems to be no disabling observer functionality. Are there any thoughts about providing it?

**Comment by WebReflection** [comment]
The idea comes from `attributeChangedCallback` which is a standard Custom Element API where, once defined which attribute you want to observe, doesn't provide a way to stop listening to changes.

However, anything as simple as the following code would work already:

```js
import attributechanged from 'attributechanged';
const observe = attributechanged({Event});

const ws = new WeakSet;
ws.add(observe(el));

el.addEventListener('attributechanged', (e) => {
  if (!ws.has(e.target)) return;
  // do anything else you need to do
});

// to disable changes
ws.delete(el);
```

That's it. When the element would get removed from the DOM and will be collectable by GC, the WeakSet, needed for this library anyway, will simply autoremove it, and the listener won't fire anymore.
